{self, ...}: let
  inherit (self) directories;
in {
  flake.modules.hjem.tmux = {
    pkgs,
    lib,
    ...
  }: let
    plugins = [
      pkgs.tmuxPlugins.continuum
      pkgs.tmuxPlugins.resurrect
      pkgs.tmuxPlugins.sessionist
      pkgs.tmuxPlugins.vim-tmux-navigator
    ];
  in {
    config = {
      packages = [pkgs.tmux pkgs.tmuxinator];

      xdg.config.files."tmux/tmux.conf".source = "${directories.config}/tmux/tmux.conf";
      xdg.config.files."tmux/theme.sh" = {
        source = "${directories.config}/tmux/theme.sh";
        executable = true;
      };
      xdg.config.files."tmux/plugins.conf".text = ''
        # Autogenerated plugins configuration
        ${(lib.concatMapStringsSep "\n\n" (plugin: ''
            # ${plugin.pname}
            run-shell ${plugin.rtp}
          '')
          plugins)}

        set -g @continuum-restore 'on'
      '';
    };
  };
}
