{self, ...}: let
  inherit (self) directories;
in {
  flake.modules.homeManager.tmux = {
    pkgs,
    lib,
    ...
  }: let
    plugins = [
      pkgs.tmuxPlugins.continuum
      pkgs.tmuxPlugins.resurrect
      pkgs.tmuxPlugins.sessionist
      pkgs.tmuxPlugins.vim-tmux-navigator
    ];
  in {
    home = {
      packages = [
        pkgs.tmux
        pkgs.tmuxinator
      ];

      file.".config/tmux/tmux.conf".source = "${directories.config}/tmux/tmux.conf";

      file.".config/tmux/theme.sh" = {
        source = "${directories.config}/tmux/theme.sh";
        executable = true;
      };

      file.".config/tmux/plugins.conf".text = ''
        # Autogenerated plugins configuration
        ${(lib.concatMapStringsSep "\n\n" (plugin: ''
            # ${plugin.pname}
            run-shell ${plugin.rtp}
          '')
          plugins)}

        set -g @continuum-restore 'on'
      '';
    };
  };
}
