pragma Singleton
import QtQuick

QtObject {
    // ==========================================================================
    // Material You Color Palette - Generated by Matugen
    // ==========================================================================
    // Source image: {{image}}
    // ==========================================================================

    // Primary colors
    readonly property color primary: "{{colors.primary.default.hex}}"
    readonly property color conPrimary: "{{colors.on_primary.default.hex}}"
    readonly property color primaryContainer: "{{colors.primary_container.default.hex}}"
    readonly property color conPrimaryContainer: "{{colors.on_primary_container.default.hex}}"
    readonly property color inversePrimary: "{{colors.inverse_primary.default.hex}}"
    readonly property color primaryFixed: "{{colors.primary_fixed.default.hex}}"
    readonly property color primaryFixedDim: "{{colors.primary_fixed_dim.default.hex}}"
    readonly property color conPrimaryFixed: "{{colors.on_primary_fixed.default.hex}}"
    readonly property color conPrimaryFixedVariant: "{{colors.on_primary_fixed_variant.default.hex}}"

    // Secondary colors
    readonly property color secondary: "{{colors.secondary.default.hex}}"
    readonly property color conSecondary: "{{colors.on_secondary.default.hex}}"
    readonly property color secondaryContainer: "{{colors.secondary_container.default.hex}}"
    readonly property color conSecondaryContainer: "{{colors.on_secondary_container.default.hex}}"
    readonly property color secondaryFixed: "{{colors.secondary_fixed.default.hex}}"
    readonly property color secondaryFixedDim: "{{colors.secondary_fixed_dim.default.hex}}"
    readonly property color conSecondaryFixed: "{{colors.on_secondary_fixed.default.hex}}"
    readonly property color conSecondaryFixedVariant: "{{colors.on_secondary_fixed_variant.default.hex}}"

    // Tertiary colors
    readonly property color tertiary: "{{colors.tertiary.default.hex}}"
    readonly property color conTertiary: "{{colors.on_tertiary.default.hex}}"
    readonly property color tertiaryContainer: "{{colors.tertiary_container.default.hex}}"
    readonly property color conTertiaryContainer: "{{colors.on_tertiary_container.default.hex}}"
    readonly property color tertiaryFixed: "{{colors.tertiary_fixed.default.hex}}"
    readonly property color tertiaryFixedDim: "{{colors.tertiary_fixed_dim.default.hex}}"
    readonly property color conTertiaryFixed: "{{colors.on_tertiary_fixed.default.hex}}"
    readonly property color conTertiaryFixedVariant: "{{colors.on_tertiary_fixed_variant.default.hex}}"

    // Error colors
    readonly property color error: "{{colors.error.default.hex}}"
    readonly property color conError: "{{colors.on_error.default.hex}}"
    readonly property color errorContainer: "{{colors.error_container.default.hex}}"
    readonly property color conErrorContainer: "{{colors.on_error_container.default.hex}}"

    // Surface colors
    readonly property color surface: "{{colors.surface.default.hex}}"
    readonly property color surfaceDim: "{{colors.surface_dim.default.hex}}"
    readonly property color surfaceBright: "{{colors.surface_bright.default.hex}}"
    readonly property color surfaceContainerLowest: "{{colors.surface_container_lowest.default.hex}}"
    readonly property color surfaceContainerLow: "{{colors.surface_container_low.default.hex}}"
    readonly property color surfaceContainer: "{{colors.surface_container.default.hex}}"
    readonly property color surfaceContainerHigh: "{{colors.surface_container_high.default.hex}}"
    readonly property color surfaceContainerHighest: "{{colors.surface_container_highest.default.hex}}"
    readonly property color conSurface: "{{colors.on_surface.default.hex}}"
    readonly property color conSurfaceVariant: "{{colors.on_surface_variant.default.hex}}"
    readonly property color surfaceVariant: "{{colors.surface_variant.default.hex}}"
    readonly property color inverseSurface: "{{colors.inverse_surface.default.hex}}"
    readonly property color inverseOnSurface: "{{colors.inverse_on_surface.default.hex}}"

    // Background colors
    readonly property color background: "{{colors.background.default.hex}}"
    readonly property color conBackground: "{{colors.on_background.default.hex}}"

    // Outline colors
    readonly property color outline: "{{colors.outline.default.hex}}"
    readonly property color outlineVariant: "{{colors.outline_variant.default.hex}}"

    // Other colors
    readonly property color shadow: "{{colors.shadow.default.hex}}"
    readonly property color scrim: "{{colors.scrim.default.hex}}"
    readonly property color sourceColor: "{{colors.source_color.default.hex}}"
}
